apiVersion: v1
kind: Service
metadata:
  name: portal-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: healthcare-app
    color: blue # Controls active traffic routing!
