groups:
- name: HealthcareSecurityAndPerformance
  rules:
  - alert: UnauthorizedAccessSpike
    expr: rate(http_server_requests_seconds_count{status="403"}[1m]) > 5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High number of 403 Unauthorized Access attempts!"
      description: "Over 5 unauthorized requests per second detected against the portal."

  - alert: HighCPULoad
    expr: process_cpu_usage > 0.85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU detected on backend pod."
