apiVersion: v1
kind: Secret
metadata:
  name: mysql-phi-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "SuperSecurePHI_RootPassword"
  MYSQL_DATABASE: "healthcare_db"
  MYSQL_USER: "phi_admin"
  MYSQL_PASSWORD: "SecurePHI_Password"
